import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                'body-md': ['Figtree'],
                'headline-md': ['Figtree'],
                'label-caps': ['Figtree'],
                'headline-sm': ['Figtree'],
                'headline-lg': ['Figtree'],
                'data-tabular': ['Figtree'],
                'body-lg': ['Figtree']
            },
            colors: {
                "error": "#ba1a1a",
                "secondary": "#4e5f78",
                "surface-dim": "#dbdad5",
                "secondary-fixed": "#d3e4ff",
                "on-primary-container": "#8292b0",
                "on-background": "#1b1c19",
                "secondary-container": "#cfe1fe",
                "surface-tint": "#4f5f7b",
                "surface-bright": "#fbf9f4",
                "tertiary-container": "#3a270c",
                "graphite": "#2D3136",
                "on-surface-variant": "#44474d",
                "inverse-primary": "#b6c7e7",
                "ivory-alt": "#F2EFE9",
                "on-error-container": "#93000a",
                "on-tertiary-container": "#aa8d6a",
                "surface-container-highest": "#e4e2dd",
                "secondary-fixed-dim": "#b6c8e4",
                "on-secondary-container": "#53647c",
                "tertiary": "#231300",
                "on-primary-fixed": "#091c34",
                "on-secondary-fixed-variant": "#37485f",
                "outline-variant": "#c5c6ce",
                "on-tertiary-fixed": "#291801",
                "primary": "#04162e",
                "primary-container": "#1a2b44",
                "primary-fixed-dim": "#b6c7e7",
                "inverse-surface": "#30312e",
                "on-primary": "#ffffff",
                "on-primary-fixed-variant": "#374762",
                "primary-fixed": "#d5e3ff",
                "surface-container": "#f0eee9",
                "on-error": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "error-container": "#ffdad6",
                "surface-container-low": "#f5f3ee",
                "surface-container-high": "#eae8e3",
                "tertiary-fixed-dim": "#e2c19b",
                "on-secondary-fixed": "#091c31",
                "on-tertiary-fixed-variant": "#594325",
                "on-surface": "#1b1c19",
                "on-tertiary": "#ffffff",
                "background": "#fbf9f4",
                "sovereign-blue": "#1A2B44",
                "surface-variant": "#e4e2dd",
                "inverse-on-surface": "#f2f1ec",
                "on-secondary": "#ffffff",
                "subtle-border": "#E5E1D9",
                "outline": "#75777e",
                "surface": "#fbf9f4",
                "tertiary-fixed": "#ffddb6",
                "ivory-base": "#F9F7F2",
                "brand": {
                  DEFAULT: '#10B981',
                  50: '#ecfdf5',
                  100: '#d1fae5',
                  200: '#a7f3d0',
                  500: '#10B981',
                  600: '#059669',
                  700: '#047857',
                  900: '#064e3b',
                },
                "sidebar": '#0F172A',
            },
            spacing: {
                "margin-mobile": "16px",
                "max-width": "1440px",
                "margin-tablet": "32px",
                "gutter": "24px",
                "margin-desktop": "48px"
            },
            boxShadow: {
                'card': '0 1px 3px 0 rgba(0, 0, 0, 0.04), 0 1px 2px -1px rgba(0, 0, 0, 0.04)',
                'subtle': '0 4px 20px -2px rgba(16, 24, 40, 0.05)',
            },
            borderRadius: {
                'card': '16px',
            }
        },
    },

    plugins: [forms],
};
